### ISSUE TITLE
libgphoto2 correctly installed, failing on preinstall script

### ISSUE THREAD

**Issue by timmythetiny** [lwille/node-gphoto2#87] opened 2016-11-07 08:23 UTC
Howdy howdy!

I have libgphoto2 and gphoto2 installed on my machine through brew.  I can use gphoto2 from the command line just fine, and I can use libgphoto2 in a C-language Xcode project as long as I set the correct compiler flags and header search paths, as generated using `pkg-config --cflags libgphoto2` and `pkg-config --libs libgphoto2`.  Likewise if I'm compiling with g++.  The Terminal output from `npm install --save gphoto2` is as follows: 

npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gphoto2@0.1.7 preinstall script '((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gphoto2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild

I don't have an installation of dpkg, `pkg-config libgphoto2` prints nothing to the console, and `brew list libgphoto2` has the following output: 

/usr/local/Cellar/libgphoto2/2.5.10/bin/gphoto2-config
/usr/local/Cellar/libgphoto2/2.5.10/bin/gphoto2-port-config
/usr/local/Cellar/libgphoto2/2.5.10/include/gphoto2/ (18 files)
/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2.6.dylib
/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port.12.dylib
/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2/ (65 files)
/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port/ (7 files)
/usr/local/Cellar/libgphoto2/2.5.10/lib/pkgconfig/ (2 files)
/usr/local/Cellar/libgphoto2/2.5.10/lib/udev/check-ptp-camera
/usr/local/Cellar/libgphoto2/2.5.10/lib/ (2 other files)
/usr/local/Cellar/libgphoto2/2.5.10/share/doc/ (54 files)
/usr/local/Cellar/libgphoto2/2.5.10/share/libgphoto2/ (6 files)
/usr/local/Cellar/libgphoto2/2.5.10/share/libgphoto2_port/0.12.0/vcamera/README.txt
/usr/local/Cellar/libgphoto2/2.5.10/share/man/ (2 files)

You may find my npm-debug.log file at https://www.dropbox.com/s/h3e4zl5jydrqlll/npm-debug.log?dl=0.  

Thanks in advance, and let me know if I can offer any further information.

**Comment by createdbyconnor** [comment] 2016-11-12 11:35
I am also having this issue.

**Comment by floooat** [comment] 2016-11-23 18:50
same here

**Comment by itamarsky** [comment] 2017-11-12 11:49
same

**Comment by itamarsky** [comment] 2017-11-12 11:51
Same

**Comment by darkbreed** [comment] 2017-11-24 20:51
Same here:

`gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/benreed/Dropbox/Development/PhotoBooth/node_modules/gphoto2
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gphoto2@0.1.7 preinstall: `((which pkg-config && pkg-config libgphoto2) || (which dpkg && dpkg -s libgphoto2-2-dev) || (which brew && brew list libgphoto2) || (echo 'ERROR: libgphoto2 seems not to be installed.' 1>&2; exit 1)) && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gphoto2@0.1.7 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benreed/.npm/_logs/2017-11-24T20_50_16_477Z-debug.log`

**Comment by darkbreed** [comment] 2017-12-01 09:52
This is happening for me on both Mac OS and Raspian.

**Comment by Sija** [comment] 2017-12-01 10:22
Duplicate of many other similar issues, #83 for instance.

**Closed** 2018-02-14 12:17 UTC
